title: "Dhuruvapriyan's Blog"
description: "Neuroscience Visualizations & Research Logs"
baseurl: ""
url: "https://dhuruvapriyan.github.io"
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

markdown: kramdown

author:
  name: "Dhuruvapriyan"

# For proper navigation on homepage
paginate: 5
paginate_path: "/page:num/"
